[package]
name = "basic_solana_program"
version = "0.1.0"
edition = "2021"
description = "A minimal Solana program example"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18.3"

[features]
no-entrypoint = []
